// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-EeM4OIcqPP-TxU1Vf0OJ18gHa9V6tE',
    appId: '1:275674125120:web:81b6b7864fa3b45d51e0a5',
    messagingSenderId: '275674125120',
    projectId: 'converse-software',
    authDomain: 'converse-software.firebaseapp.com',
    storageBucket: 'converse-software.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSDblK5gENwnmIefw9aI-E8XKJT9QkhxQ',
    appId: '1:275674125120:android:60d7309764e2352051e0a5',
    messagingSenderId: '275674125120',
    projectId: 'converse-software',
    storageBucket: 'converse-software.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ZumDqQntmDsLKHs4fDPo25tRRwtHa_0',
    appId: '1:275674125120:ios:d054899289785d3251e0a5',
    messagingSenderId: '275674125120',
    projectId: 'converse-software',
    storageBucket: 'converse-software.appspot.com',
    androidClientId:
        '275674125120-5jl9cnrgvedogpo989i15f1p2e6qe3l9.apps.googleusercontent.com',
    iosClientId:
        '275674125120-7q3f2h72j7a1s1rnp9vvksa5pifm29js.apps.googleusercontent.com',
    iosBundleId: 'tech.sarthakz25.converse',
  );
}
